### ISSUE TITLE
4.0.0 Release to-do list for the github repository

### ISSUE THREAD

**Issue by Ringenberg** [CMUCTAT/CTAT#1]
Things that need to be done on this repository once CTAT 4.0.0 is officially released:
- [x]  Tag the repository
- [x]  Update example links in wiki to use https://cdn.rawgit.com/CMUCTAT/CTAT/v4.0.0/...
- [x]  Remove Examples/js/ctat.min.js and double check that all examples link to https://cdn.ctat.cs.cmu.edu/releases/latest/ctat.min.js
- [x]  Remove Examples/css/CTAT.css and Examples/css/CTAT.min.css and check that all examples link to https://cdn.ctat.cs.cmu.edu/releases/latest/CTAT.css or https://cdn.ctat.cs.cmu.edu/releases/latest/CTAT.min.css

**Comment by Ringenberg** [comment]
See http://rawgit.com/ for more information on why using cdn.rawgit.com is better.

**Comment by Ringenberg** [comment]
Code is tagged and wiki has been updated to use cdn.rawgit.
